In [1]:
# Import libraries
import pandas as pd
import numpy as np

# Load dataset
file_name = r"C:\Users\Lenovo\Desktop\cardio_digital_twin_project\data\raw\heart.csv"
df = pd.read_csv(file_name)

print("Dataset loaded successfully")
print("Shape:", df.shape)
# Show first 5 rows
df.head()

Dataset loaded successfully
Shape: (1025, 14)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0

In [2]:
# Create age groups
df['age_group'] = pd.cut(df['age'], bins=[0,40,55,70,100], labels=[0,1,2,3])

print("Age group feature created")
df[['age', 'age_group']].head()

Age group feature created

   age age_group
0   52         1
1   53         1
2   70         2
3   61         2
4   62         2

In [3]:
# Heart stress = oldpeak * exang
df['heart_stress'] = df['oldpeak'] * df['exang']

print("Heart stress feature created")
df[['oldpeak', 'exang', 'heart_stress']].head()

Heart stress feature created

   oldpeak  exang  heart_stress
0      1.0      0           0.0
1      3.1      1           3.1
2      2.6      1           2.6
3      0.0      0           0.0
4      1.9      0           0.0

In [4]:
# Interaction feature
df['bp_chol'] = df['trestbps'] * df['chol']

print("BP-Cholesterol interaction feature created")
df[['trestbps', 'chol', 'bp_chol']].head()

BP-Cholesterol interaction feature created

   trestbps  chol  bp_chol
0       125   212    26500
1       140   203    28420
2       145   174    25230
3       148   203    30044
4       138   294    40572

In [5]:
X = df.drop("target", axis=1)
y = df["target"]

print("Features and target separated")
print("Features shape:", X.shape)

Features and target separated
Features shape: (1025, 16)

In [6]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("Train-test split completed")
print("Training size:", X_train.shape)
print("Testing size:", X_test.shape)

Train-test split completed
Training size: (820, 16)
Testing size: (205, 16)

In [7]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

print("Feature scaling completed")

Feature scaling completed

In [8]:
import joblib

joblib.dump(X_train, "C:/Users/Lenovo/Desktop/cardio_digital_twin_project/data/processed/X_train_fe.pkl")
joblib.dump(X_test, "C:/Users/Lenovo/Desktop/cardio_digital_twin_project/data/processed/X_test_fe.pkl")
joblib.dump(y_train, "C:/Users/Lenovo/Desktop/cardio_digital_twin_project/data/processed/y_train_fe.pkl")
joblib.dump(y_test, "C:/Users/Lenovo/Desktop/cardio_digital_twin_project/data/processed/y_test_fe.pkl")

joblib.dump(scaler, "C:/Users/Lenovo/Desktop/cardio_digital_twin_project/data/processed/scaler_fe.pkl")

print("Feature engineered data saved successfully")

Feature engineered data saved successfully